CREATE TABLE IF NOT EXISTS ueba (
    num INT NOT NULL,
    id INT PRIMARY KEY,
    uid VARCHAR(255) NOT NULL,
    domain VARCHAR(255) NOT NULL,
    cn VARCHAR(255),
    department VARCHAR(255),
    title VARCHAR(255),
    who VARCHAR(255),
    logon_count INTEGER,
    num_logons7 INTEGER,
    num_share7 INTEGER,
    num_file7 INTEGER,
    num_ad7 INTEGER,
    num_n7 INTEGER,
    num_logons14 INTEGER,
    num_share14 INTEGER,
    num_file14 INTEGER,
    num_ad14 INTEGER,
    num_n14 INTEGER,
    num_logons30 INTEGER,
    num_share30 INTEGER,
    num_file30 INTEGER,
    num_ad30 INTEGER,
    num_n30 INTEGER,
    num_logons150 INTEGER,
    num_share150 INTEGER,
    num_file150 INTEGER,
    num_ad150 INTEGER,
    num_n150 INTEGER,
    num_logons365 INTEGER,
    num_share365 INTEGER,
    num_file365 INTEGER,
    num_ad365 INTEGER,
    num_n365 INTEGER,
    has_user_principal_name INTEGER,
    has_mail INTEGER,
    has_phone INTEGER,
    flag_disabled INTEGER,
    flag_lockout INTEGER,
    flag_password_not_required INTEGER,
    flag_password_cant_change INTEGER,
    flag_dont_expire_password INTEGER,
    owned_files INTEGER,
    num_mailboxes INTEGER,
    num_member_of_groups INTEGER,
    num_member_of_indirect_groups INTEGER,
    member_of_indirect_groups_ids varchar(1024),
    member_of_groups_ids varchar(1024),
    is_admin INTEGER,
    is_service INTEGER
);

COPY ueba(num,id,uid,domain,cn,department,title,who,logon_count,num_logons7,num_share7,num_file7,num_ad7,num_n7,num_logons14,num_share14,num_file14,num_ad14,num_n14,num_logons30,num_share30,num_file30,num_ad30,num_n30,num_logons150,num_share150,num_file150,num_ad150,num_n150,num_logons365,num_share365,num_file365,num_ad365,num_n365,has_user_principal_name,has_mail,has_phone,flag_disabled,flag_lockout,flag_password_not_required,flag_password_cant_change,flag_dont_expire_password,owned_files,num_mailboxes,num_member_of_groups,num_member_of_indirect_groups,member_of_indirect_groups_ids,member_of_groups_ids,is_admin,is_service)
FROM '/docker-entrypoint-initdb.d/ueba.csv'
DELIMITER ','
CSV HEADER;